server:
  port: 9003
spring:
  application:
    name: love-story-daily
  cloud:
    nacos:
      discovery:
        server-addr: 39.99.160.188:8848
        username: nacos
        password: Dzkj_nacos