server:
  port: 9002
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  application:
    name: love-story-journey
  #文件上次大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love-story?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 39.99.160.188:8848
        username: nacos
        password: Dzkj_nacos