# 服务端口
server:
  port: 8888
# 服务应用名称
spring:
  application:
    name: love-story-gateway
  # nacos注册发现配置
  cloud:
    nacos:
      discovery:
        username: nacos
        password: Dzkj_nacos
        server-addr: 39.99.160.188:8848
    # 网关路由配置
    gateway:
      routes:
        - id: witness_router #路由的唯一标识
          uri: lb://love-story-witness # 需要转发的地址 使用nacos的负载均衡功能
          predicates: # 断言规则，用于路由的怕匹配
            - Path=/love/witness/**
        - id: witness_router #路由的唯一标识
          uri: lb://love-story-journey # 需要转发的地址 使用nacos的负载均衡功能
          predicates: # 断言规则，用于路由的怕匹配
            - Path=/love/journey/**
        - id: witness_router #路由的唯一标识
          uri: lb://love-story-daily # 需要转发的地址 使用nacos的负载均衡功能
          predicates: # 断言规则，用于路由的怕匹配
            - Path=/love/daily/**
        - id: witness_router #路由的唯一标识
          uri: lb://love-story-friend # 需要转发的地址 使用nacos的负载均衡功能
          predicates: # 断言规则，用于路由的怕匹配
            - Path=/love/friend/**

